const projects = {
  p1: {
    title: "Fassadeentwicklung mit Stable Diffusion",
    content: `
      <p>
        Tools: Krea Ai, Prome Ai.
      </p>
      <img src="images/p1_Cover image.png" alt="Cover Image">
      <p>
        Exploration of facade design by fine tuning a Stable Diffusion model
        and ControlNet. It was done using Krea ai, which allows for LoRa training.
      </p>
        <img src="images/p1_data training.png" alt="DAta sample used for training">
      <p>
        After training, various facade designs were generated by
        providing different input images and prompts to the model.
      </p>
      <img src="images/p1_controlnet input.png" alt="ControlNet Input Example">
      <img src="images/p1_controlnet input 2.png" alt="ControlNet Input Example">
      <p>
        By using ControlNet, specific structural features could be
        emphasized in the generated images.
      </p>
      <img src="images/p1_krea facade original and edited.png" alt="final facade designs">
      <p>
        The resutling ideas were later treated to fit into the facade concept.
      </p>
      

    `
  },

  p2: {
    title: "Flux Lora Training – Glass Distortion",
    content: `
      <p>
        Tools: Flux Schnell model, Comfy UI.
      </p>
      <p>
        Custom LoRA training focused on glass distortion effects
        for architectural visualization.
      </p>

      <img src="images/p2_training data sample.jpg" alt="Glass distortion study">

      <p>
        For this experiment sample photos were used to train a custom LoRa to achive the effect.
      </p>
      <p>
        The training was done using Comfy UI, an open source Stable Diffusion interface.
        And it was done on a local machine with a Nvidia RTX 5070 GPU.
      </p>
      <img src="images/p2_exterior render.jpg" alt="Glass distortion exterior render">
      <p>
        The resulting LoRa was then used to generate architectural visualizations
        with glass distortion effects.
      </p>
      <img src="images/p2_interior render.jpg" alt="Glass distortion interior render">
      <p>
        Both exterior and interior renders were created to showcase the effect.
      </p>
      <p>
        The experiment demonstrates the potential of custom LoRa training
        for enhancing architectural visualizations with specific effects.
      </p>
      <img src="images/p2_applied on human figure.jpg" alt="Glass distortion Woman">
      <p>
        It even generated some interesting results when prompted on a human figure
      </p>
    `
  }
};
