const projects = {
  p1: {
    title: "Fassadeentwicklung mit Stable Diffusion",
    content: `
      <p>
        Tools: Stable Diffusion, ControlNet.
      </p>
      <img src="images/p1_Cover image.png" alt="Cover Image">
      <p>
        Exploration of facade design by fine tuning a Stable Diffusion model
        and ControlNet. It was done using Krea ai, which allows for LoRa training.
      </p>
        <img src="images/p1_data training.png" alt="DAta sample used for training">
      <p>
        After training, various facade designs were generated by
        providing different input images and prompts to the model.
      </p>
      <img src="images/p1_controlnet input.png" alt="ControlNet Input Example">
      <img src="images/p1_controlnet input 2.png" alt="ControlNet Input Example">
      <p>
        By using ControlNet, specific structural features could be
        emphasized in the generated images.
      </p>
      <img src="images/p1_krea facade original and edited.png" alt="final facade designs">
      <p>
        The resutling ideas were later treated to fit into the facade concept.
      </p>
      

    `
  },

  p2: {
    title: "Flux Lora Training – Glass Distortion",
    content: `
      <h3>Flux Lora Training – Glass Distortion</h3>

      <p>
        Custom LoRA training focused on glass distortion effects
        for architectural visualization.
      </p>

      <img src="images/project2.jpg" alt="Glass distortion study">

      <p>
        Experiments with dataset curation and prompt control.
      </p>
    `
  }
};
